# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabmaster', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='num_stars',
            field=models.DecimalField(blank=True, decimal_places=5, default='', max_digits=7),
        ),
    ]
